### ISSUE TITLE
Quote conversion regression 

### ISSUE THREAD

**Issue by nicoloboschi** [radkovo/jStyleParser#80]
Switching from 2.1 to 3.1, I noticed that quote inside css rules are not rightly converted.
Code:
`   <style>            
            .myclass {
                background:url('my&quot;img.gif');
            }
   </style>
` 

In 2.1 the result was:
`
        <div style="background: url('my&quot;img.gif');" id="ref1" class="myclass" ></div>
`
In 3.0 >=:
`
         <div style="background: url('my\&quot\;img.gif');" id="ref1" class="myclass" ></div>
`
It seems it are not able to convert quotes anymore.

**Comment by eolivelli** [comment]
@radkovo I will try to send a reproducer my collegue @nicoloboschi did not write the code to reproduce the problem

**Comment by radkovo** [comment]
I/O escaping is provided by the third-party [unbescape](https://github.com/unbescape/unbescape) library. It seems that the ampersand escaping was added there in version 1.1.4 by [this commit](https://github.com/unbescape/unbescape/commit/03e66a7a2dd39f2ab6154dc872492308647279d8) (the explanation is provided there). Generally, it seems reasonable because even your example actually demonstrates a potential security problem (you transfer an XHTML entity from the CSS code, where it **is not** interpreted as a quote to the (X)HTML attribute where it **is** interpreted as a quote. If someone sends you a file named like that, it actually *may* be an attempt to break your system. Just for curiosity, what is the reason for using HTML entities in CSS URLs?

On the other hand, you are right that the result probably does not fully correspond to the CSS syntax. It may be a good idea to report this to the unbescape project.

As a temporary fix, you could override the unbescape dependency in your `pom.xml` to the version `1.1.3.RELEASE` that behaves the old way.

**Comment by eolivelli** [comment]
@radkovo I have to dig into this problem on the downstream application, maybe it is not a jstyleparser issue. To the css parser we should send pure css code and that &quote; should be unescaped before  sending  the css code to jstyleparser

**Comment by eolivelli** [comment]
I have downgraded ubescape
